### PR TITLE
Version bump for nodejs, electron, serialport and others

### PR DESCRIPTION
**Pull request by poWer4aiX**
Hi Peter, as promised I have tried to update to a more recent version of electron, as the one currently been used is no longer supported. Upgrade to V20 was not working (is also very fresh), but upgrading to V19. I have done all tests and build with nodejs 16.17.0

I have tested the code directly in VS Code under Ubuntu 22.04, as well with the generated appimage:
- opening / closing / opening cycles from tray is working
- UI is working
- 3Dview is working
- serial ports a found
- change on serial port gets notified
- connect to is working
- moving my machine (Lead1010 with Blackbox) is running fine.
There is one minor issue related to Chromium, which seems to be know ([file open dialog hangs Chrome](https://bugs.launchpad.net/ubuntu/+source/gtk+3.0/+bug/1970047)) but could be solved by changing the following setting:
```bash
$ gsettings set org.gnome.desktop.sound input-feedback-sounds false
```

Unfortunately I'm missing a VisualStudio so I cannot test the change in Window..

### CODE REVIEW

**Comment by petervanderwalt** [comment]
Thanks! Looking over the updated packages, may I ask you if you have moment to test:
- avrgirl - used by the Firmware Flashing tool - just make sure you can flash Grbl succesfully?
- drivelist - used by the Prepare USB for Interface under the Wizards and tools menu: See if a flashdrive pops up in the dropdown when you insert it, and goes away when removed

**Comment by poWer4aiX** [comment]
Further tests made:
* *drivelist - used by the Prepare USB for Interface under the Wizards and tools menu: See if a flashdrive pops up in the dropdown when you insert it, and goes away when removed*
=> Flashdrive pops up in the list of drives when I insert a flash-drive, and gets removed once I pull it out.

* *avrgirl - used by the Firmware Flashing tool - just make sure you can flash Grbl succesfully?*
I used the FW Flashing Tool to burn the FW into the Blackbox, by selecting "3Axes CNC/Laser: Dual-Y...", and seems to succeed:
```
[21:20:53] [ disconnect ] PORT INFO: Port closed
[21:20:54] [ Firmware Upgrade ] connected
[21:20:54] [ Firmware Upgrade ] reset complete.
[21:20:54] [ Firmware Upgrade ] flashing, please wait...
[21:21:16] [ Firmware Upgrade ]  flash complete.
```

**Comment by petervanderwalt** [comment]
Thanks! Merging! (:

**Comment by petervanderwalt** [comment]
Yeah we'll have to stay on 16 for a little longer, Drivelist need >14 and <16 

$ npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'drivelist@11.0.2',
npm WARN EBADENGINE   **required: { node: '>=14 < 16' },**
npm WARN EBADENGINE   current: { node: 'v18.12.0', npm: '8.19.2' }
npm WARN EBADENGINE }

**Comment by poWer4aiX** [comment]
Oh, seems that I missed this :-( Well there is a pending [PR to support <v19 ](https://github.com/balena-io-modules/drivelist/pull/410), so let's hope they will merge it soon. As [v14 will run out of security updates maintenance](https://endoflife.date/nodejs) in approx. 5 months, an upgrade seems to be required...

**Comment by petervanderwalt** [comment]
For sure! Soon soon! (: 
Glad its the only one still holding us back - rest looks good - thanks again!

**Pull request merged**
