### PR TITLE
feat(probe/safety): require probe to be touched before probing

### PR DESCRIPTION
**Pull request by tippfehlr**
This change forces touching the probe (closing the circuit) to enable the probe button.
Can not be configured right now, maybe a setting somewhere would be appropriate.

### CODE REVIEW

**Comment by petervanderwalt** [comment]
OK gave it some thought. Can avoid the config, if we just update the text there to say something like either Clicking confirm, or touching the probe.  (no config needed, either option clicks the button for you, enabling the Probe button) 

Then code to watch P pin status and execute existing confirmProbeInPlace() function if it it is, while probe wizard is open

image


I am stuck on another project, but will merge if anyone want to take a go at it.

**Comment by tippfehlr** [comment]
I like that, I only fear that folks won’t read and just press the button. 

What about renaming the button to e.g. `touch not possible`?

(I guess it’s their fault for not reading though)

**Comment by petervanderwalt** [comment]
> I like that, I only fear that folks won’t read and just press the button.
That's in a way the point. Keep it working the way it always has, the existing videos stay valid, old habits stay going without needing that quick 1second mental block because something is different, etc.  Implement a visible change and it results in a need to reshoot videos, or support tickets for "i can no longer see the Confirm button" (yes it happens) 

The existing way has worked quite well.  You can't continue until you click the button - in practise enough to get the guys who forget the clip to do so then.  If they power through without checking that's on them.   This just provides another way to do the same, and for some might feel more secure (i know it works too) - win and win?

**Comment by tippfehlr** [comment]
That is understandable, I’ll do that. Give me a few weeks though

**Comment by tippfehlr** [comment]
this should do it. I will test this later on a real cnc.

**Comment by tippfehlr** [comment]
Tested & works; ready for merging :)

**Pull request merged**
